# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character] 
success_symbol = '[ğŸ¥¢](bold green)' 
error_symbol = '[ğŸ’¢](bold red)' 
vimcmd_symbol = '[ğŸ¡](bold yellow)' 
vimcmd_replace_symbol = '[ğŸ¥¢](bold yellow)' 
vimcmd_replace_one_symbol = '[ğŸ¥¢](bold yellow)' 
vimcmd_visual_symbol = '[ğŸ¥](bold red)' 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

